### ISSUE TITLE
"Streaming-ready" API for Android App

### ISSUE THREAD

**Issue by Bradleykingz** [caprica/choonio#43]
Hey. This is an amazing project you've got going on here.

I was a big fan of Play Music as well. Shame it got plugged, but that's just the way it goes I guess.

I want to build an Android app with this project as the base backend. Of course, I'd prefer  to make as few modifications as possible to the backend, but I'd be willing to if it's completely necessary.

What would it take to make this app "streaming-ready"?

**Comment by caprica** [comment]
Essentially, instead of having the vlcj media player play the media locally, you use that same media player but you have to set it up to use VLC's streaming output.

This is done by setting various "sout" (streaming-output) options when the vlcj media player factory is created, and/or similar options when each media is played (via "media options").

I would start by looking at the vlcj examples that include "stream" in their name, here https://github.com/caprica/vlcj-examples.

Probably necessary for a solution is that you can set the media player up with various "keep" options to keep the same stream alive when new media is played.

But that is only one part of it.

You would need to change the frontend to use an HTML5 media player component that obtained the streaming URLs. With the current code, what is happening is that the server is playing the media, whereas what you need for a streaming solution is for the client to play the media.

Finally you need to work out how to generate your streaming URLs, pass them to the client, and hook it all up with an in-browser media player.

It should all be doable, but it might not be straightforward, but it's certainly a non-trivial set of changes that would be needed.

**Comment by caprica** [comment]
Oh sorry, I just re-read your comment and see you were going to write an Android app anyway, so yes that would address one half of what I was saying above.

So this reduces your problems to:

 - change the backend media player to use VLC's sout options;
 - find a way to pass streaming URLs to your frontend app;
 - or, have a single streaming URL that you keep feeding with new media (sout-keep options) but then you have to think about the stream failing and reestablishing it, multiple devices etc.

Again, it's doable.

But what I would say, for me, this project's reason for existing is for the Google Play UI experience (initially at least on desktop). So I find more value personally in the front-end than the back-end.

There are surely dedicated, and more mature, streaming server solutions already out there you could use for your backend.

**Comment by Bradleykingz** [comment]
Thanks for the quick reply! It's going to come in handy when I actually begin the work.

> There are surely dedicated, and more mature, streaming server solutions already out there you could use for your backend.

I'm mostly doing this for the experience, tbh. Taking a look at your code, I've noticed there's lots of things I could learn already, lol. 

That said, I haven't found any readily-available streaming servers in either NodeJS or Java (Spring Boot, to be exact). This is the closest open source solution I've found, and it looks pretty comprehensive to me. Perhaps I'll have to make a whole lot of modifications. but it sure beats starting from scratch 😅 

> But what I would say, for me, this project's reason for existing is for the Google Play UI experience

I never used Play Music on the web, so I can't relate, unfortunately. I would really like an app that allows me to upload, backup, and organize my playlists though. I haven't found any, so I think I'll build one 🤷.

Thanks again for the help. I'll close this issue and get started with vlcj.

Hope I can ping you if I have more questions.

Cheers.
